# ===================================
#  Relation Behavior Config
# ===================================

logs:
    label: keerill.users::lang.logs.label
    view:
        list: $/keerill/users/models/log/columns.yaml
        recordsPerPage: 10
        showCheckboxes: false
        toolbarButtons: false

accesslogs:
    label: keerill.users::lang.logs.label
    view:
        list: $/keerill/users/models/accesslog/columns.yaml
        recordsPerPage: 10
        showCheckboxes: false
        toolbarButtons: false

revision_history:
    label: keerill.users::lang.user.revision.label
    view:
        list: $/keerill/users/models/user/revision.yaml
        recordsPerPage: 10
        showCheckboxes: false
        toolbarButtons: false