# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: keerill.users::lang.user.label

# Model Form Field configuration
form: $/keerill/users/models/user/fields.yaml

# Model Class name
modelClass: KEERill\Users\Models\User

# Default redirect location
defaultRedirect: keerill/users/users

# Create page
create:
    title: keerill.users::lang.users.create_title
    redirect: keerill/users/users/preview/:id
    redirectClose: keerill/users/users

# Update page
update:
    title: keerill.users::lang.users.update_title
    redirect: keerill/users/users/update/:id
    redirectClose: keerill/users/users

# Preview page
preview:
    title: keerill.users::lang.users.preview_title
    redirect: keerill/users/users/preview/:id
