# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: $/october/users/models/user/columns.yaml

# Model Class name
modelClass: Keerill\Users\Models\User

# List Title
title: Управление пользователями

# Link URL for each record
recordUrl: october/users/users/preview/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 20

# Filter widget configuration
filter: config_filter.yaml

# Displays the list column set up button
showSetup: true

# Displays the sorting link on each column
showSorting: true

# Default sorting column
defaultSort:
    column: created_at
    direction: desc

# Display checkboxes next to each record
showCheckboxes: true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt
