# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: User

# Model Form Field configuration
form: $/keerill/users/models/user/fields.yaml

# Model Class name
modelClass: KEERill\Users\Models\User

# Default redirect location
defaultRedirect: keerill/users/users

# Create page
create:
    title: Создание пользователя
    redirect: keerill/users/users/preview/:id
    redirectClose: keerill/users/users

# Update page
update:
    title: Редактирования пользователя
    redirect: keerill/users/users
    redirectClose: keerill/users/users

# Preview page
preview:
    title: Просмотр профиля пользователя
