# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Группа

# Model Form Field configuration
form: $/keerill/users/models/group/fields.yaml

# Model Class name
modelClass: KEERill\Users\Models\Group

# Default redirect location
defaultRedirect: keerill/users/groups

# Create page
create:
    title: Создание
    redirect: keerill/users/groups/update/:id
    redirectClose: keerill/users/groups

# Update page
update:
    title: Редактирование
    redirect: keerill/users/groups
    redirectClose: keerill/users/groups