# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: keerill.users::lang.group.label

# Model Form Field configuration
form: $/keerill/users/models/group/fields.yaml

# Model Class name
modelClass: KEERill\Users\Models\Group

# Default redirect location
defaultRedirect: keerill/users/groups

# Create page
create:
    title: keerill.users::lang.groups.create_title
    redirect: keerill/users/groups/update/:id
    redirectClose: keerill/users/groups

# Update page
update:
    title: keerill.users::lang.groups.update_title
    redirect: keerill/users/groups
    redirectClose: keerill/users/groups