# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Group

# Model Form Field configuration
form: $/keerill/users/models/group/fields.yaml

# Model Class name
modelClass: KEERill\Users\Models\Group

# Default redirect location
defaultRedirect: keerill/users/groups

# Create page
create:
    title: Create Group
    redirect: keerill/users/groups/update/:id
    redirectClose: keerill/users/groups

# Update page
update:
    title: Edit Group
    redirect: keerill/users/groups
    redirectClose: keerill/users/groups

# Preview page
preview:
    title: Preview Group
