# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Permission

# Model Form Field configuration
form: $/keerill/users/models/permission/fields.yaml

# Model Class name
modelClass: KEERill\Users\Models\Permission

# Default redirect location
defaultRedirect: keerill/users/permissions

# Create page
create:
    title: Create Permission
    redirect: keerill/users/permissions/update/:id
    redirectClose: keerill/users/permissions

# Update page
update:
    title: Edit Permission
    redirect: keerill/users/permissions
    redirectClose: keerill/users/permissions

# Preview page
preview:
    title: Preview Permission
